# Generated by Django 5.2.8 on 2026-05-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(upload_to='media/animals/images'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Confirmed'), ('R', 'Rejected'), ('D', 'Completed'), ('X', 'Cancelled'), ('N', 'No Show')], default='P', max_length=1),
        ),
    ]
